CC=gcc  #compiler
TARGET=test_mesinkata #target file name
SOURCE= tes_mesinkata.c mesinkata.c ..\MesinKarakter\mesinkarakter.c
all:
	$(CC) $(SOURCE) -o $(TARGET)
	@echo "Build finished. Run './$(TARGET)' to execute."
clean:
	rm $(TARGET)
