CC=gcc  #compiler
TARGET=test_mesinkarakter #target file name
SOURCE= mesinkarakter.c test_mesinkarakter.c
all:
	$(CC) $(SOURCE) -o $(TARGET)
	@echo "Build finished. Run './$(TARGET)' to execute."
clean:
	rm $(TARGET)
