CC=gcc  #compiler
TARGET=test_listlagu #target file name
SOURCE= ../Word/word.c listlagu.c ../Lagu/lagu.c test_listlagu.c -o test_listlagu
all:
	$(CC) $(SOURCE) -o $(TARGET)
	@echo "Build finished. Run './$(TARGET)' to execute."
clean:
	rm $(TARGET)
