CC=gcc  #compiler
TARGET=test_map #target file name
SOURCE= test_map.c map.c ../Word/word.c ../SetWord/set.c
all:
	$(CC) $(SOURCE) -o $(TARGET)
	@echo "Build finished. Run './$(TARGET)' to execute."
clean:
	rm $(TARGET)
