CC=gcc  #compiler
TARGET=main #target file name

all:
	$(CC) ADT/StackLagu/stack.c ADT/Queue/queue.c ADT/SetWord/set.c ADT/Word/word.c ADT/ListLagu/listlagu.c ADT/MesinKarakter/mesinkarakter.c ADT/MesinKata/mesinkata.c main.c console/src/console.c ADT/Lagu/lagu.c ADT/MapWord/map.c ADT/Playlist/playlist.c ADT/Playlist/listlinier.c DecTree.c -o $(TARGET)
	@echo "Build finished. Run './$(TARGET)' to execute."
clean:
	rm $(TARGET)
